language: python
python:
  - "2.7"
  - "3.1"
  - "3.6"
  

env:
  - FLASK=0.12.2
 
# installing dependencies
install: 
  "pip install -r requirements.txt"

# command to run tests
script: pytest tests/test_app.py 

after_success: coveralls
